a = int(input("Enter integer: "))
b = float(input("Enter float: "))
c = input("Enter string: ")
d = bool(input("Enter boolean: "))
print("Integer =", a)
print("Float =", b)
print("String =", c)
print("Boolean =", d)
